In [1]:
import pandas as pd

In [2]:
df1=pd.read_csv("/demoDB.Allibeth.csv")
df1

,_id,profile_url,first_name,middle_name,last_name,image_url,office_name,address,description,website,...,agent_phone_numbers[0],office_phone_numbers[0],office_phone_numbers[1],social.facebook_url,social.twitter_url,social.linkedin_url,social.other_urls[0],social.other_urls[1],social.other_urls[2],languages[0]
0,674593dd63f3d792c1408011,https://www.alliebeth.com/bio/aaroncarroll,Aaron,NaN,Carroll,https://content.mediastg.net/dynamic/RealEstat...,NaN,"3838 Oak Lawn Ave, Suite 500","A Texas native, Aaron Carroll was raised in Ty...",NaN,...,214-205-6043,(214) 521-7355,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,674593dd63f3d792c1408012,https://www.alliebeth.com/bio/aimeeforman,Aimee,NaN,Forman,https://content.mediastg.net/dynamic/RealEstat...,NaN,"550 Reserve St, Suite 320",Aimee is a member of the Keoughan Group with A...,NaN,...,682-465-3008,(817) 697-4900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,674593dd63f3d792c1408013,https://www.alliebeth.com/bio/AlanSmith,Alan,NaN,Smith,https://content.mediastg.net/dynamic/RealEstat...,NaN,"6318 Gaston Ave, Suite 200",With more than 20 years of experience and over...,NaN,...,214-914-1343,(214) 302-5780,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,674593dd63f3d792c1408014,https://www.alliebeth.com/bio/alciemassman,Alcie,NaN,Massman,https://content.mediastg.net/dynamic/RealEstat...,NaN,"3838 Oak Lawn Ave, Suite 500","Unbeknownst to her at the time, Alcies real es...",NaN,...,214-679-8934,(214) 521-7355,NaN,https://www.facebook.com/AlcieMassman.Compass,NaN,NaN,https://www.instagram.com/alciemassman.realtor/,NaN,NaN,NaN
4,674593dd63f3d792c1408015,https://www.alliebeth.com/bio/AlexisCollard,Alexis,NaN,Collard,https://content.mediastg.net/dynamic/RealEstat...,NaN,"3838 Oak Lawn Ave, Suite 500","Not only is Alexis a sixth generation Texan, b...",NaN,...,214-893-3038,(214) 521-7355,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439,674593dd63f3d792c14081c8,https://www.alliebeth.com/bio/VictoriaWiman,Victoria,NaN,Wiman,https://content.mediastg.net/dynamic/RealEstat...,NaN,"3838 Oak Lawn Ave, Suite 500","A long time resident of the Dallas metroplex, ...",NaN,...,214-770-0695,(214) 521-7355,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
440,674593dd63f3d792c14081c9,https://www.alliebeth.com/bio/VincentMcGrath,Vincent,NaN,McGrath,https://content.mediastg.net/dynamic/RealEstat...,NaN,"3838 Oak Lawn Ave, Suite 500",The wide ranging experiences of Vincent McGrat...,NaN,...,214-797-0661,(214) 521-7355,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
441,674593dd63f3d792c14081ca,https://www.alliebeth.com/bio/WendyJohnson,Wendy,NaN,Johnson,https://content.mediastg.net/dynamic/RealEstat...,NaN,"3838 Oak Lawn Ave, Suite 500","A native of Baton Rouge, LA, Wendy and her fam...",NaN,...,214-500-4504,(214) 521-7355,NaN,https://www.facebook.com/WendyJohnson.alliebeth,NaN,NaN,https://www.instagram.com/wendyjohnson_realest...,NaN,NaN,NaN
442,674593dd63f3d792c14081cb,https://www.alliebeth.com/bio/WynneMoore,Wynne,NaN,Moore,https://content.mediastg.net/dynamic/RealEstat...,NaN,"550 Reserve St, Suite 320","Wynne Moore, Executive Vice-President of Allie...",NaN,...,817-781-7060,(817) 697-4900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
443,674593dd63f3d792c14081cc,https://www.alliebeth.com/bio/yolandaford,Yolanda,NaN,Badovinus-Ford,https://content.mediastg.net/dynamic/RealEstat...,NaN,"3838 Oak Lawn Ave, Suite 500",Yoli Badovinus-Ford is a highly accomplished a...,NaN,...,214-923-4892,(214) 521-7355,NaN,NaN,NaN,NaN,https://www.instagram.com/yolandabadovinus,NaN,NaN,NaN

In [3]:
df1.columns

Index(['_id', 'profile_url', 'first_name', 'middle_name', 'last_name',
       'image_url', 'office_name', 'address', 'description', 'website',
       'email', 'title', 'country', 'city', 'zipcode', 'state',
       'agent_phone_numbers[0]', 'office_phone_numbers[0]',
       'office_phone_numbers[1]', 'social.facebook_url', 'social.twitter_url',
       'social.linkedin_url', 'social.other_urls[0]', 'social.other_urls[1]',
       'social.other_urls[2]', 'languages[0]'],
      dtype='object')

In [6]:
df1.shape

(444, 26)

In [8]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 444 entries, 0 to 443
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   _id                      444 non-null    object
 1   profile_url              444 non-null    object
 2   first_name               444 non-null    object
 3   middle_name              19 non-null     object
 4   last_name                444 non-null    object
 5   image_url                443 non-null    object
 6   office_name              0 non-null      float64
 7   address                  444 non-null    object
 8   description              444 non-null    object
 9   website                  55 non-null     object
 10  email                    0 non-null      float64
 11  title                    428 non-null    object
 12  country                  444 non-null    object
 13  city                     444 non-null    object
 14  zipcode                  444 non-null    int64
 15  state                    444 non-null    object
 16  agent_phone_numbers[0]   436 non-null    object
 17  office_phone_numbers[0]  444 non-null    object
 18  office_phone_numbers[1]  5 non-null      object
 19  social.facebook_url      16 non-null     object
 20  social.twitter_url       1 non-null      object
 21  social.linkedin_url      6 non-null      object
 22  social.other_urls[0]     47 non-null     object
 23  social.other_urls[1]     3 non-null      object
 24  social.other_urls[2]     1 non-null      object
 25  languages[0]             6 non-null      object
dtypes: float64(2), int64(1), object(23)
memory usage: 90.3+ KB

In [9]:
import re
from urllib.parse import urlparse

In [10]:
url_column = 'profile_url'
urls = df1[url_column]

In [11]:
missing_urls = df1[url_column].isnull().sum()
print(f"Missing URLs: {missing_urls}")

Missing URLs: 0

In [12]:
def is_valid_url(url):
    regex = re.compile(
        r'^(https?|ftp)://'  # URL must start with http or https
        r'(([A-Z0-9.-]+)+(:[A-Z0-9]*)?)(:[0-9]{1,5})?'
        r'(/?|[/?]\S+)$', re.IGNORECASE)
    return re.match(regex, url) is not None

df1['valid_url'] = df1[url_column].apply(lambda x: is_valid_url(x) if pd.notnull(x) else False)

In [14]:
df1['valid_url']

0      True
1      True
2      True
3      True
4      True
       ...
439    True
440    True
441    True
442    True
443    True
Name: valid_url, Length: 444, dtype: bool

In [15]:
duplicate_urls = df1[url_column].duplicated().sum()
print(f"\nDuplicate URLs: {duplicate_urls}")

Duplicate URLs: 0